service: my-service

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 2048
  stage: dev
  timeout: 30
  region: ap-south-1

functions:
  hello:
    handler: handler.hello
    events:
      - http: ANY /{proxy+}
      - http: ANY /
