// const PDFDocument = require('pdfkit');
// const express = require('express');
// const app = express();
// const port = 3000;

// const generatePDF = (data, res) => {
//     const doc = new PDFDocument();

//     res.setHeader('Content-Type', 'application/pdf');
//     res.setHeader('Content-Disposition', 'inline; filename="flight-booking-details.pdf"');

//     doc.pipe(res);

//     doc
//         .fontSize(20)
//         .text('Flight Booking Details', { align: 'center' }) 
//         .moveDown(1);

//     doc
//         .fontSize(12)
//         .text(`From: ${data.from || 'Not specified'}`, { align: 'left' })
//         .moveDown(0.5);

//     doc
//         .text(`To: ${data.to || 'Not specified'}`, { align: 'left' })
//         .moveDown(0.5);

//     doc
//         .text(`Date: ${data.date || 'Not specified'}`, { align: 'left' })
//         .moveDown(0.5);

//     doc
//         .text(`Flight Number: ${data.flightNumber || 'Not specified'}`, { align: 'left' })
//         .moveDown(0.5);

//     doc
//         .text(`Boarding Time: ${data.boardingTime || 'Not specified'}`, { align: 'left' })
//         .moveDown(0.5);

//     doc
//         .text(`Service Provider: ${data.serviceProvider || 'Not specified'}`, { align: 'left' })
//         .moveDown(0.5);

//     doc
//         .moveDown(1)
//         .fontSize(10)
//         .text('Generated by Your Company Name', { align: 'center' });

//     doc.on('error', (err) => {
//         console.error('Error during PDF generation:', err);
//         res.status(500).send('Error generating PDF');
//     });

//     doc.end();
// };

// let downloadPdf = async function(req, res){
//     try {
//         generatePDF(req.body, res)

//         return res.status(200).send({status: true, message: "pdf downloaded"})
//     } catch (error) {
//         return res.status(500).send({status: false, message: error.message})
//     }
// }

// module.exports = { downloadPdf }

const PDFDocument = require('pdfkit');
const express = require('express');
const fs = require('fs');
const path = require('path');
const app = express();

const generatePDF = (data, outputPath) => {
    return new Promise((resolve, reject) => {
        const doc = new PDFDocument();
        const writeStream = fs.createWriteStream(outputPath);

        doc.pipe(writeStream);

        doc
            .fontSize(20)
            .text('Flight Booking Details', { align: 'center' }) // Title
            .moveDown(1); // Move down one line

        // Adding dynamic data fields
        doc
            .fontSize(12)
            .text(`From: ${data.from || 'Not specified'}`, { align: 'left' })
            .moveDown(0.5);

        doc
            .text(`To: ${data.to || 'Not specified'}`, { align: 'left' })
            .moveDown(0.5);

        doc
            .text(`Date: ${data.date || 'Not specified'}`, { align: 'left' })
            .moveDown(0.5);

        doc
            .text(`Flight Number: ${data.flightNumber || 'Not specified'}`, { align: 'left' })
            .moveDown(0.5);

        doc
            .text(`Boarding Time: ${data.boardingTime || 'Not specified'}`, { align: 'left' })
            .moveDown(0.5);

        doc
            .text(`Service Provider: ${data.serviceProvider || 'Not specified'}`, { align: 'left' })
            .moveDown(0.5);

        doc
            .moveDown(1)
            .fontSize(10)
            .text('Generated by Your Company Name', { align: 'center' });

        doc.end();

        writeStream.on('finish', () => resolve(outputPath));
        writeStream.on('error', reject);
    });
};

let downloadPdf = async function (req, res) {
    try {
        const outputPath = path.join(__dirname, `output-${Date.now()}.pdf`)

        await generatePDF(req.body, outputPath);

        res.send(`
            <h1>PDF Generated Successfully!</h1>
            <a href="/download/${path.basename(outputPath)}" download>Click here to download the PDF</a>
        `);
    } catch (error) {
        return res.status(500).send({ status: false, message: error.message })
    }
}

let download = async function (req, res) {
    let filename = req.params.filename
    const filePath = path.join(__dirname, filename);

    // Check if the file exists
    if (fs.existsSync(filePath)) {
        res.download(filePath, (err) => {
            if (err) {
                console.error('Error sending file:', err);
                res.status(500).send('Error sending file');
            }
        });
    } else {
        res.status(404).send('File not found');
    }
}

module.exports = { downloadPdf, download }